# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-01-25 11:41
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_auto_20170125_1137'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='courseresource',
            options={'verbose_name': '\u8bfe\u7a0b\u8d44\u6e90', 'verbose_name_plural': '\u8bfe\u7a0b\u8d44\u6e90'},
        ),
    ]
