# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-02-05 11:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0008_lesson_learn_times'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lesson',
            name='learn_times',
        ),
        migrations.AddField(
            model_name='video',
            name='learn_times',
            field=models.IntegerField(default=0, verbose_name='\u5b66\u4e60\u957f\u5ea6\uff08\u5206\u949f\u6570\uff09'),
        ),
    ]
