# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-02-04 16:01
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20170125_0104'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='iamge',
            new_name='image',
        ),
    ]
